FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Installer les outils de build et la toolchain ARM gcc
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi \
    git \
    && rm -rf /var/lib/apt/lists/*